openapi: 3.0.0
info:
  description: API for the 7th CHECK24 GenDev challenge providing product offerings
    from five different internet providers
  title: CHECK24 GenDev 7 API
  version: dev
servers:
- description: Local development server
  url: http://localhost:8080
- description: Production server
  url: https://check24-gendev-7-api.janez.at/api
paths:
  /health:
    get:
      description: Returns the status of the API
      operationId: healthCheck
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'
          description: Successful health check
      summary: Health check endpoint
      tags:
      - Health
  /version:
    get:
      description: Returns version information about the API
      operationId: getVersion
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Version'
          description: Successful version retrieval
      summary: Version information endpoint
      tags:
      - System
components:
  schemas:
    Health:
      description: Health check response
      example:
        status: ok
      properties:
        status:
          example: ok
          type: string
      type: object
      x-go-type: Health
    Version:
      description: Version information response
      example:
        version: 1.0.0
        buildDate: 2025-04-21T12:00:00Z
        commitHash: abc123def456
      properties:
        version:
          description: The semantic version of the API
          example: 1.0.0
          type: string
        buildDate:
          description: The date and time when the API was built
          example: 2025-04-21T12:00:00Z
          format: date-time
          type: string
        commitHash:
          description: The git commit hash of the API build
          example: abc123def456
          type: string
      type: object
      x-go-type: Version
