# Config file for [Air](https://github.com/air-verse/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main cmd/check24-gendev-7-server/main.go"
bin = "tmp/main"
# args_bin = ["-debug"]
include_ext = ["go", "json"]

exclude_dir = []
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
follow_symlink = true
# log = "air.log"
# Poll files for changes instead of using fsnotify.
poll = false
# Stop running old binary when build errors occur.
stop_on_error = true
send_interrupt = true
kill_delay = 500 # nanosecond

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true
