FROM golang:1.24-alpine

# Install Air for live reload
RUN go install github.com/air-verse/air@latest

WORKDIR /app

# Copy your Go module files
COPY go.mod go.sum ./
RUN go mod download


# Run Air (auto-reload) with default config
CMD ["air", "-c", ".air.toml"]