/**
 * CHECK24 GenDev 7 API
 * API for the 7th CHECK24 GenDev challenge providing product offerings from five different internet providers
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class AbsoluteDiscount {
    'valueInCent': number;
    'minOrderValueInCent'?: number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: { [index: string]: string } | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "valueInCent",
            "baseName": "valueInCent",
            "type": "number",
            "format": "uint32"
        },
        {
            "name": "minOrderValueInCent",
            "baseName": "minOrderValueInCent",
            "type": "number",
            "format": "uint32"
        }];

    static getAttributeTypeMap() {
        return AbsoluteDiscount.attributeTypeMap;
    }

    public constructor() {
    }
}
