/**
 * CHECK24 GenDev 7 API
 * API for the 7th CHECK24 GenDev challenge providing product offerings from five different internet providers
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
* Type of internet connection
*/
export enum ConnectionType {
    Dsl = 'DSL',
    Cable = 'CABLE',
    Fiber = 'FIBER',
    Mobile = 'MOBILE'
}
