/**
 * CHECK24 GenDev 7 API
 * API for the 7th CHECK24 GenDev challenge providing product offerings from five different internet providers
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Pricing } from '../models/Pricing';
import { ProductInfo } from '../models/ProductInfo';

export class InternetProduct {
    'id': string;
    'provider': string;
    'name': string;
    'description'?: string;
    /**
    * Date when the product was offered
    */
    'dateOffered': Date;
    'productInfo': ProductInfo;
    'pricing': Pricing;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: { [index: string]: string } | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "provider",
            "baseName": "provider",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "dateOffered",
            "baseName": "dateOffered",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "productInfo",
            "baseName": "productInfo",
            "type": "ProductInfo",
            "format": ""
        },
        {
            "name": "pricing",
            "baseName": "pricing",
            "type": "Pricing",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return InternetProduct.attributeTypeMap;
    }

    public constructor() {
    }
}
