/**
 * CHECK24 GenDev 7 API
 * API for the 7th CHECK24 GenDev challenge providing product offerings from five different internet providers
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
* Response containing a list of internet products and version info
*/
export class InternetProductsCursor {
    'version'?: string;
    /**
    * Cursor to retrieve the first batch of products
    */
    'nextCursor'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: { [index: string]: string } | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "nextCursor",
            "baseName": "nextCursor",
            "type": "string",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return InternetProductsCursor.attributeTypeMap;
    }

    public constructor() {
    }
}
