/**
 * CHECK24 GenDev 7 API
 * API for the 7th CHECK24 GenDev challenge providing product offerings from five different internet providers
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InternetProduct } from '../models/InternetProduct';

/**
* Response containing a list of internet products
*/
export class InternetProductsResponse {
    'products'?: Array<InternetProduct>;
    /**
    * Cursor to retrieve the next batch of products, or null if finished
    */
    'nextCursor'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: { [index: string]: string } | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "products",
            "baseName": "products",
            "type": "Array<InternetProduct>",
            "format": ""
        },
        {
            "name": "nextCursor",
            "baseName": "nextCursor",
            "type": "string",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return InternetProductsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
