/**
 * CHECK24 GenDev 7 API
 * API for the 7th CHECK24 GenDev challenge providing product offerings from five different internet providers
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class PercentageDiscount {
    /**
    * discount rate, e.g. 15 for 15%
    */
    'percentage': number;
    'maxDiscountInCent'?: number | null;
    'durationInMonths'?: number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: { [index: string]: string } | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "percentage",
            "baseName": "percentage",
            "type": "number",
            "format": "uint32"
        },
        {
            "name": "maxDiscountInCent",
            "baseName": "maxDiscountInCent",
            "type": "number",
            "format": "uint32"
        },
        {
            "name": "durationInMonths",
            "baseName": "durationInMonths",
            "type": "number",
            "format": "uint32"
        }];

    static getAttributeTypeMap() {
        return PercentageDiscount.attributeTypeMap;
    }

    public constructor() {
    }
}
