/**
 * CHECK24 GenDev 7 API
 * API for the 7th CHECK24 GenDev challenge providing product offerings from five different internet providers
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AbsoluteDiscount } from '../models/AbsoluteDiscount';
import { PercentageDiscount } from '../models/PercentageDiscount';
import { SubsequentCost } from '../models/SubsequentCost';

export class Pricing {
    'monthlyCostInCent': number;
    'contractDurationInMonths'?: number | null;
    'minContractDurationInMonths'?: number | null;
    'maxAgeInJears'?: number | null;
    'minOrderValueInCent'?: number | null;
    'minAgeInYears'?: number | null;
    'installationServiceIncluded'?: boolean;
    'subsequentCosts'?: SubsequentCost | null;
    'absoluteDiscount'?: AbsoluteDiscount | null;
    'percentageDiscount'?: PercentageDiscount | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: { [index: string]: string } | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "monthlyCostInCent",
            "baseName": "monthlyCostInCent",
            "type": "number",
            "format": ""
        },
        {
            "name": "contractDurationInMonths",
            "baseName": "contractDurationInMonths",
            "type": "number",
            "format": ""
        },
        {
            "name": "minContractDurationInMonths",
            "baseName": "minContractDurationInMonths",
            "type": "number",
            "format": ""
        },
        {
            "name": "maxAgeInJears",
            "baseName": "maxAgeInJears",
            "type": "number",
            "format": ""
        },
        {
            "name": "minOrderValueInCent",
            "baseName": "minOrderValueInCent",
            "type": "number",
            "format": ""
        },
        {
            "name": "minAgeInYears",
            "baseName": "minAgeInYears",
            "type": "number",
            "format": ""
        },
        {
            "name": "installationServiceIncluded",
            "baseName": "installationServiceIncluded",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "subsequentCosts",
            "baseName": "subsequentCosts",
            "type": "SubsequentCost",
            "format": ""
        },
        {
            "name": "absoluteDiscount",
            "baseName": "AbsoluteDiscount",
            "type": "AbsoluteDiscount",
            "format": ""
        },
        {
            "name": "percentageDiscount",
            "baseName": "PercentageDiscount",
            "type": "PercentageDiscount",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return Pricing.attributeTypeMap;
    }

    public constructor() {
    }
}
