/**
 * CHECK24 GenDev 7 API
 * API for the 7th CHECK24 GenDev challenge providing product offerings from five different internet providers
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConnectionType } from '../models/ConnectionType';

export class ProductInfo {
    /**
    * in Mbps
    */
    'speed': number;
    'connectionType': ConnectionType;
    'tv'?: string | null;
    'unthrottledCapacityMb'?: number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: { [index: string]: string } | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "speed",
            "baseName": "speed",
            "type": "number",
            "format": ""
        },
        {
            "name": "connectionType",
            "baseName": "connectionType",
            "type": "ConnectionType",
            "format": ""
        },
        {
            "name": "tv",
            "baseName": "tv",
            "type": "string",
            "format": ""
        },
        {
            "name": "unthrottledCapacityMb",
            "baseName": "unthrottledCapacityMb",
            "type": "number",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return ProductInfo.attributeTypeMap;
    }

    public constructor() {
    }
}


