/**
 * CHECK24 GenDev 7 API
 * API for the 7th CHECK24 GenDev challenge providing product offerings from five different internet providers
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class SubsequentCost {
    'monthlyCostInCent': number;
    'startMonth': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: { [index: string]: string } | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "monthlyCostInCent",
            "baseName": "monthlyCostInCent",
            "type": "number",
            "format": ""
        },
        {
            "name": "startMonth",
            "baseName": "startMonth",
            "type": "number",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return SubsequentCost.attributeTypeMap;
    }

    public constructor() {
    }
}
