/**
 * CHECK24 GenDev 7 API
 * API for the 7th CHECK24 GenDev challenge providing product offerings from five different internet providers
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
* Version information response
*/
export class Version {
    /**
    * The semantic version of the API
    */
    'version'?: string;
    /**
    * The date and time when the API was built
    */
    'buildDate'?: Date;
    /**
    * The git commit hash of the API build
    */
    'commitHash'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: { [index: string]: string } | undefined = undefined;

    static readonly attributeTypeMap: Array<{ name: string, baseName: string, type: string, format: string }> = [
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "buildDate",
            "baseName": "buildDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "commitHash",
            "baseName": "commitHash",
            "type": "string",
            "format": ""
        }];

    static getAttributeTypeMap() {
        return Version.attributeTypeMap;
    }

    public constructor() {
    }
}
