// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CHECK24 GenDev 7 API
 *
 * API for the 7th CHECK24 GenDev challenge providing product offerings from five different internet providers
 *
 * API version: dev
 */

package api

import (
	"context"

	"github.com/rotmanjanez/check24-gendev-7/config"
	"github.com/rotmanjanez/check24-gendev-7/pkg/interfaces"
	"github.com/rotmanjanez/check24-gendev-7/pkg/models"
)

// InternetProductsAPIService is a service that implements the logic for the InternetProductsAPIServicer
// This service should implement the business logic for every endpoint for the InternetProductsAPI API.
// Include any external packages or services that will be required by this service.
type InternetProductsAPIService struct {
	config    *config.Config
	providers []interfaces.ProviderAdapter
}

// NewInternetProductsAPIService creates a default api service
func NewInternetProductsAPIService(cfg *config.Config, providers []interfaces.ProviderAdapter) *InternetProductsAPIService {
	return &InternetProductsAPIService{
		config:    cfg,
		providers: providers,
	}
}

// GetInternetProducts -
func (s *InternetProductsAPIService) GetInternetProducts(ctx context.Context, address models.Address) (ImplResponse, error) {
	return Response(200, []models.InternetProduct{}), nil
}
