// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CHECK24 GenDev 7 API
 *
 * API for the 7th CHECK24 GenDev challenge providing product offerings from five different internet providers
 *
 * API version: 1.0.0
 */

package api

import (
	"context"

	"github.com/rotmanjanez/check24-gendev-7/pkg/models"
)

// HealthAPIService is a service that implements the logic for the HealthAPIServicer
// This service should implement the business logic for every endpoint for the HealthAPI API.
// Include any external packages or services that will be required by this service.
type HealthAPIService struct {
}

// NewHealthAPIService creates a default api service
func NewHealthAPIService() *HealthAPIService {
	return &HealthAPIService{}
}

// HealthCheck - Health check endpoint
func (s *HealthAPIService) HealthCheck(ctx context.Context) (ImplResponse, error) {
	return Response(200, models.Health{
		Status: "ok",
	}), nil
}
