// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CHECK24 GenDev 7 API
 *
 * API for the 7th CHECK24 GenDev challenge providing product offerings from five different internet providers
 *
 * API version: dev
 */

package api

import "log/slog"

// Response return a ImplResponse struct filled
func Response(code int, body interface{}, headers ...map[string]string) ImplResponse {
	resp := ImplResponse{
		Code: code,
		Body: body,
	}
	if len(headers) > 1 {
		slog.Warn("More than one header map provided, only the first will be used")
	}
	if len(headers) > 0 {
		resp.Headers = headers[0]
	}

	return resp
}
