// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CHECK24 GenDev 7 API
 *
 * API for the 7th CHECK24 GenDev challenge providing product offerings from five different internet providers
 *
 * API version: dev
 */

package api

// ImplResponse defines an implementation response with error code and the associated body
type ImplResponse struct {
	Code    int
	Body    interface{}
	Headers map[string]string
}
