// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CHECK24 GenDev 7 API
 *
 * API for the 7th CHECK24 GenDev challenge providing product offerings from five different internet providers
 *
 * API version: dev
 */

package models

// Health - Health check response
type Health struct {
	Status string `json:"status,omitempty"`
}

// AssertHealthRequired checks if the required fields are not zero-ed
func AssertHealthRequired(obj Health) error {
	return nil
}

// AssertHealthConstraints checks if the values respects the defined constraints
func AssertHealthConstraints(obj Health) error {
	return nil
}
