// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CHECK24 GenDev 7 API
 *
 * API for the 7th CHECK24 GenDev challenge providing product offerings from five different internet providers
 *
 * API version: dev
 */

package models

import (
	"encoding"
	"encoding/json"
)

// SharedInternetProductsResponse - Response containing a list of shared internet products
type SharedInternetProductsResponse struct {
	Products []InternetProduct `json:"products,omitempty"`

	Version string `json:"version,omitempty"`

	Address Address `json:"Address,omitempty"`
}

// AssertSharedInternetProductsResponseRequired checks if the required fields are not zero-ed
func AssertSharedInternetProductsResponseRequired(obj SharedInternetProductsResponse) error {
	for _, el := range obj.Products {
		if err := AssertInternetProductRequired(el); err != nil {
			return err
		}
	}
	if err := AssertAddressRequired(obj.Address); err != nil {
		return err
	}
	return nil
}

// AssertSharedInternetProductsResponseConstraints checks if the values respects the defined constraints
func AssertSharedInternetProductsResponseConstraints(obj SharedInternetProductsResponse) error {
	for _, el := range obj.Products {
		if err := AssertInternetProductConstraints(el); err != nil {
			return err
		}
	}
	if err := AssertAddressConstraints(obj.Address); err != nil {
		return err
	}
	return nil
}

// Implementation of the BinaryMarshaller interface
func (obj SharedInternetProductsResponse) MarshalBinary() ([]byte, error) {
	return json.Marshal(obj)
}

// Implementation of the BinaryUnmarshaller interface
func (obj *SharedInternetProductsResponse) UnmarshalBinary(data []byte) error {
	return json.Unmarshal(data, obj)
}

// Ensure that InternetProduct implements the BinaryMarshaler and BinaryUnmarshaler interfaces
var _ encoding.BinaryMarshaler = (*SharedInternetProductsResponse)(nil)
var _ encoding.BinaryUnmarshaler = (*SharedInternetProductsResponse)(nil)
