// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * CHECK24 GenDev 7 API
 *
 * API for the 7th CHECK24 GenDev challenge providing product offerings from five different internet providers
 *
 * API version: dev
 */

package models

import (
	"errors"
)

type SubsequentCost struct {
	MonthlyCostInCent int32 `json:"monthlyCostInCent"`

	StartMonth int32 `json:"startMonth"`
}

// AssertSubsequentCostRequired checks if the required fields are not zero-ed
func AssertSubsequentCostRequired(obj SubsequentCost) error {
	elements := map[string]interface{}{
		"monthlyCostInCent": obj.MonthlyCostInCent,
		"startMonth":        obj.StartMonth,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertSubsequentCostConstraints checks if the values respects the defined constraints
func AssertSubsequentCostConstraints(obj SubsequentCost) error {
	if obj.MonthlyCostInCent < 0 {
		return &ParsingError{Param: "MonthlyCostInCent", Err: errors.New(ErrMsgMinValueConstraint)}
	}
	if obj.StartMonth < 0 {
		return &ParsingError{Param: "StartMonth", Err: errors.New(ErrMsgMinValueConstraint)}
	}
	return nil
}
